### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by mjallday** [balanced/billy#55]
I created a new virtualenv and installed billy by running `python setup.py develop && pip install -r requirements.txt`

Next, I tried to run `initialize_billy_db development.ini`

```
| ~/code/balanced/billy @ mjallday-2  (billy)(master) 
| => initialize_billy_db development.ini
Traceback (most recent call last):
  File "/Users/marshall/.virtualenvs/billy/bin/initialize_billy_db", line 9, in <module>
    load_entry_point('billy==0.0.1', 'console_scripts', 'initialize_billy_db')()
  File "/Users/marshall/code/balanced/billy/billy/scripts/initializedb.py", line 27, in main
    settings = setup_database({}, **settings)
  File "/Users/marshall/code/balanced/billy/billy/models/__init__.py", line 18, in setup_database
    engine_from_config(settings, 'sqlalchemy.')
  File "/Users/marshall/.virtualenvs/billy/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-macosx-10.8-x86_64.egg/sqlalchemy/engine/__init__.py", line 351, in engine_from_config
    return create_engine(url, **opts)
  File "/Users/marshall/.virtualenvs/billy/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-macosx-10.8-x86_64.egg/sqlalchemy/engine/__init__.py", line 332, in create_engine
    return strategy.create(*args, **kwargs)
  File "/Users/marshall/.virtualenvs/billy/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-macosx-10.8-x86_64.egg/sqlalchemy/engine/strategies.py", line 64, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/Users/marshall/.virtualenvs/billy/lib/python2.7/site-packages/SQLAlchemy-0.8.2-py2.7-macosx-10.8-x86_64.egg/sqlalchemy/dialects/sqlite/pysqlite.py", line 295, in dbapi
    raise e
ImportError: No module named pysqlite2
```

Running `pip install pysqlite` fixes the issue but I'm not sure if the dependency is incorrect or if it's missing.

**Comment by fangpenlin** [comment]
hummm... odd, sqlite3 is a build-in package, it should be there in most cases, did you turn it off when you were compiling python from source code? As I see it should be OSX you are using there. Maybe it is caused by the virtualenv? Could you import sqlite3 in the real Python environment? Try

python -c "import sqlite3"
