### ISSUE TITLE
`vagrant up` not running successfully for me on OSX

### ISSUE THREAD

**Issue by mjallday** [balanced/billy#60]
I get the following output:

``` sh
| => vagrant up
Failed to load the "vagrant-butcher" plugin. View logs for more details.

Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'precise64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Mounting shared folders...
[default] -- /vagrant
[default] -- /tmp/vagrant-chef-1/chef-solo-1/cookbooks
[default] Running provisioner: shell...
[default] Running: inline script
stdin: is not a tty
Successfully installed mixlib-cli-1.3.0
Successfully installed net-ssh-2.7.0
Successfully installed chef-11.6.0
3 gems installed
[default] Running provisioner: chef_solo...
Generating chef JSON and uploading...
Running chef-solo...
stdin: is not a tty
[2013-10-08T15:54:37+00:00] INFO: Forking chef instance to converge...
[2013-10-08T15:54:37+00:00] INFO: *** Chef 11.6.0 ***
[2013-10-08T15:54:37+00:00] INFO: Setting the run_list to ["recipe[billy]"] from JSON
[2013-10-08T15:54:37+00:00] INFO: Run List is [recipe[billy]]
[2013-10-08T15:54:37+00:00] INFO: Run List expands to [billy]
[2013-10-08T15:54:37+00:00] INFO: Starting Chef Run for precise64
[2013-10-08T15:54:37+00:00] INFO: Running start handlers
[2013-10-08T15:54:37+00:00] INFO: Start handlers complete.
[2013-10-08T15:54:38+00:00] INFO: ohai plugins will be at: /etc/chef/ohai_plugins
[2013-10-08T15:54:38+00:00] INFO: remote_directory[/etc/chef/ohai_plugins] created directory /etc/chef/ohai_plugins
[2013-10-08T15:54:38+00:00] INFO: remote_directory[/etc/chef/ohai_plugins] mode changed to 755
[2013-10-08T15:54:38+00:00] INFO: cookbook_file[/etc/chef/ohai_plugins/README] created file /etc/chef/ohai_plugins/README
[2013-10-08T15:54:38+00:00] INFO: cookbook_file[/etc/chef/ohai_plugins/README] updated file contents /etc/chef/ohai_plugins/README
[2013-10-08T15:54:38+00:00] INFO: cookbook_file[/etc/chef/ohai_plugins/README] mode changed to 644
[2013-10-08T15:54:38+00:00] INFO: ohai[custom_plugins] reloaded
[2013-10-08T15:54:43+00:00] INFO: execute[apt-get-update-build-essentials] ran successfully
[2013-10-08T15:55:05+00:00] WARN: Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)
[2013-10-08T15:55:05+00:00] WARN: Current  service[nginx]: /tmp/vagrant-chef-1/chef-solo-1/cookbooks/nginx/recipes/source.rb:114:in `from_file'
[2013-10-08T15:55:05+00:00] WARN: Cloning resource attributes for execute[apt-get update] from prior resource (CHEF-3694)
[2013-10-08T15:55:05+00:00] WARN: Previous execute[apt-get update]: /tmp/vagrant-chef-1/chef-solo-1/cookbooks/apt/recipes/default.rb:29:in `from_file'
[2013-10-08T15:55:05+00:00] WARN: Current  execute[apt-get update]: /tmp/vagrant-chef-1/chef-solo-1/cookbooks/postgresql/recipes/ruby.rb:27:in `from_file'
[2013-10-08T15:55:09+00:00] INFO: execute[apt-get update] ran successfully
[2013-10-08T15:55:34+00:00] INFO: execute[apt-get-update] ran successfully
[2013-10-08T15:55:36+00:00] INFO: package[update-notifier-common] sending run action to execute[apt-get-update] (immediate)
[2013-10-08T15:55:41+00:00] INFO: execute[apt-get-update] ran successfully
[2013-10-08T15:55:41+00:00] INFO: directory[/var/cache/local] created directory /var/cache/local
[2013-10-08T15:55:41+00:00] INFO: directory[/var/cache/local] owner changed to 0
[2013-10-08T15:55:41+00:00] INFO: directory[/var/cache/local] group changed to 0
[2013-10-08T15:55:41+00:00] INFO: directory[/var/cache/local] mode changed to 755
[2013-10-08T15:55:41+00:00] INFO: directory[/var/cache/local/preseeding] created directory /var/cache/local/preseeding
[2013-10-08T15:55:41+00:00] INFO: directory[/var/cache/local/preseeding] owner changed to 0
[2013-10-08T15:55:41+00:00] INFO: directory[/var/cache/local/preseeding] group changed to 0
[2013-10-08T15:55:41+00:00] INFO: directory[/var/cache/local/preseeding] mode changed to 755
[2013-10-08T15:56:01+00:00] INFO: remote_file[/var/chef/cache/ez_setup.py] created file /var/chef/cache/ez_setup.py
[2013-10-08T15:56:02+00:00] INFO: remote_file[/var/chef/cache/ez_setup.py] updated file contents /var/chef/cache/ez_setup.py
[2013-10-08T15:56:02+00:00] INFO: remote_file[/var/chef/cache/ez_setup.py] mode changed to 644
[2013-10-08T15:56:02+00:00] INFO: remote_file[/var/chef/cache/get-pip.py] created file /var/chef/cache/get-pip.py
[2013-10-08T15:56:03+00:00] INFO: remote_file[/var/chef/cache/get-pip.py] updated file contents /var/chef/cache/get-pip.py
[2013-10-08T15:56:03+00:00] INFO: remote_file[/var/chef/cache/get-pip.py] mode changed to 644
[2013-10-08T15:56:03+00:00] INFO: execute[install-setuptools] ran successfully
[2013-10-08T15:56:05+00:00] INFO: execute[install-pip] ran successfully
[2013-10-08T15:56:05+00:00] INFO: Installing python_pip[virtualenv] version latest
[2013-10-08T15:56:06+00:00] INFO: user[www-data] altered
[2013-10-08T15:56:07+00:00] INFO: template[/etc/chef/ohai_plugins/nginx.rb] created file /etc/chef/ohai_plugins/nginx.rb
[2013-10-08T15:56:07+00:00] INFO: template[/etc/chef/ohai_plugins/nginx.rb] updated file contents /etc/chef/ohai_plugins/nginx.rb
[2013-10-08T15:56:07+00:00] INFO: template[/etc/chef/ohai_plugins/nginx.rb] owner changed to 0
[2013-10-08T15:56:07+00:00] INFO: template[/etc/chef/ohai_plugins/nginx.rb] group changed to 0
[2013-10-08T15:56:07+00:00] INFO: template[/etc/chef/ohai_plugins/nginx.rb] mode changed to 755
[2013-10-08T15:56:07+00:00] INFO: template[/etc/chef/ohai_plugins/nginx.rb] sending reload action to ohai[reload_nginx] (immediate)
[2013-10-08T15:56:07+00:00] INFO: ohai[reload_nginx] reloaded
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx] created directory /etc/nginx
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx] owner changed to 0
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx] group changed to 0
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx] mode changed to 755
[2013-10-08T15:56:07+00:00] INFO: directory[/var/log/nginx] created directory /var/log/nginx
[2013-10-08T15:56:07+00:00] INFO: directory[/var/log/nginx] owner changed to 33
[2013-10-08T15:56:07+00:00] INFO: directory[/var/log/nginx] mode changed to 755
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/sites-available] created directory /etc/nginx/sites-available
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/sites-available] owner changed to 0
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/sites-available] group changed to 0
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/sites-available] mode changed to 755
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/sites-enabled] created directory /etc/nginx/sites-enabled
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/sites-enabled] owner changed to 0
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/sites-enabled] group changed to 0
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/sites-enabled] mode changed to 755
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/conf.d] created directory /etc/nginx/conf.d
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/conf.d] owner changed to 0
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/conf.d] group changed to 0
[2013-10-08T15:56:07+00:00] INFO: directory[/etc/nginx/conf.d] mode changed to 755
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxensite] created file /usr/sbin/nxensite
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxensite] updated file contents /usr/sbin/nxensite
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxensite] owner changed to 0
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxensite] group changed to 0
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxensite] mode changed to 755
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxdissite] created file /usr/sbin/nxdissite
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxdissite] updated file contents /usr/sbin/nxdissite
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxdissite] owner changed to 0
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxdissite] group changed to 0
[2013-10-08T15:56:07+00:00] INFO: template[/usr/sbin/nxdissite] mode changed to 755
[2013-10-08T15:56:10+00:00] INFO: remote_file[http://nginx.org/download/nginx-1.2.9.tar.gz] created file /var/chef/cache/nginx-1.2.9.tar.gz
[2013-10-08T15:56:10+00:00] INFO: remote_file[http://nginx.org/download/nginx-1.2.9.tar.gz] updated file contents /var/chef/cache/nginx-1.2.9.tar.gz
[2013-10-08T15:56:10+00:00] INFO: template[nginx.conf] created file /etc/nginx/nginx.conf
[2013-10-08T15:56:10+00:00] INFO: template[nginx.conf] updated file contents /etc/nginx/nginx.conf
[2013-10-08T15:56:10+00:00] INFO: template[nginx.conf] owner changed to 0
[2013-10-08T15:56:10+00:00] INFO: template[nginx.conf] group changed to 0
[2013-10-08T15:56:10+00:00] INFO: template[nginx.conf] mode changed to 644
[2013-10-08T15:56:10+00:00] INFO: template[/etc/nginx/sites-available/default] created file /etc/nginx/sites-available/default
[2013-10-08T15:56:10+00:00] INFO: template[/etc/nginx/sites-available/default] updated file contents /etc/nginx/sites-available/default
[2013-10-08T15:56:10+00:00] INFO: template[/etc/nginx/sites-available/default] owner changed to 0
[2013-10-08T15:56:10+00:00] INFO: template[/etc/nginx/sites-available/default] group changed to 0
[2013-10-08T15:56:10+00:00] INFO: template[/etc/nginx/sites-available/default] mode changed to 644
[2013-10-08T15:56:10+00:00] INFO: template[/etc/nginx/sites-available/default] not queuing delayed action reload on service[nginx] (delayed), as it's already been queued
[2013-10-08T15:56:11+00:00] INFO: execute[nxensite default] ran successfully
[2013-10-08T15:56:11+00:00] INFO: execute[nxensite default] not queuing delayed action reload on service[nginx] (delayed), as it's already been queued
[2013-10-08T15:56:11+00:00] INFO: cookbook_file[/etc/nginx/mime.types] created file /etc/nginx/mime.types
[2013-10-08T15:56:11+00:00] INFO: cookbook_file[/etc/nginx/mime.types] updated file contents /etc/nginx/mime.types
[2013-10-08T15:56:11+00:00] INFO: cookbook_file[/etc/nginx/mime.types] owner changed to 0
[2013-10-08T15:56:11+00:00] INFO: cookbook_file[/etc/nginx/mime.types] group changed to 0
[2013-10-08T15:56:11+00:00] INFO: cookbook_file[/etc/nginx/mime.types] mode changed to 644
[2013-10-08T15:56:11+00:00] INFO: cookbook_file[/etc/nginx/mime.types] not queuing delayed action reload on service[nginx] (delayed), as it's already been queued
[2013-10-08T15:56:34+00:00] INFO: bash[compile_nginx_source] ran successfully
[2013-10-08T15:56:34+00:00] WARN: Method 'template_location' of 'Chef::Provider::Template' is deprecated. It will be removed in Chef 12.
[2013-10-08T15:56:34+00:00] WARN: Please update your cookbooks accordingly. Accessed from:
[2013-10-08T15:56:34+00:00] WARN: /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.6.0/bin/../lib/chef/provider/package.rb:207:in `preseed_resource'
[2013-10-08T15:56:34+00:00] WARN: /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.6.0/bin/../lib/chef/provider/package.rb:182:in `get_preseed_file'
[2013-10-08T15:56:34+00:00] WARN: /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.6.0/bin/../lib/chef/provider/package.rb:73:in `action_install'
[2013-10-08T15:56:34+00:00] WARN: /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.6.0/bin/../lib/chef/provider.rb:114:in `send'
[2013-10-08T15:56:34+00:00] WARN: Method 'template_finder' of 'Chef::Provider::Template' is deprecated. It will be removed in Chef 12.
[2013-10-08T15:56:34+00:00] WARN: Please update your cookbooks accordingly. Accessed from:
[2013-10-08T15:56:34+00:00] WARN: /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.6.0/bin/../lib/chef/deprecation/provider/template.rb:42:in `template_location'
[2013-10-08T15:56:34+00:00] WARN: /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.6.0/bin/../lib/chef/deprecation/warnings.rb:30:in `template_location'
[2013-10-08T15:56:34+00:00] WARN: /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.6.0/bin/../lib/chef/provider/package.rb:207:in `preseed_resource'
[2013-10-08T15:56:34+00:00] WARN: /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/chef-11.6.0/bin/../lib/chef/provider/package.rb:182:in `get_preseed_file'
[2013-10-08T15:56:34+00:00] INFO: cookbook_file[/var/chef/cache/preseed/runit/runit-2.1.1-6.2ubuntu2.seed] created file /var/chef/cache/preseed/runit/runit-2.1.1-6.2ubuntu2.seed
[2013-10-08T15:56:34+00:00] INFO: cookbook_file[/var/chef/cache/preseed/runit/runit-2.1.1-6.2ubuntu2.seed] updated file contents /var/chef/cache/preseed/runit/runit-2.1.1-6.2ubuntu2.seed
[2013-10-08T15:56:34+00:00] INFO: package[runit] pre-seeding package installation instructions
[2013-10-08T15:56:36+00:00] INFO: package[runit] sending nothing action to execute[start-runsvdir] (immediate)
[2013-10-08T15:56:36+00:00] INFO: package[runit] sending nothing action to execute[runit-hup-init] (immediate)
[2013-10-08T15:56:36+00:00] INFO: directory[/etc/sv/nginx] created directory /etc/sv/nginx
[2013-10-08T15:56:36+00:00] INFO: directory[/etc/sv/nginx] mode changed to 755
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/run] created file /etc/sv/nginx/run
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/run] updated file contents /etc/sv/nginx/run
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/run] mode changed to 755
[2013-10-08T15:56:36+00:00] INFO: directory[/etc/sv/nginx/log] created directory /etc/sv/nginx/log
[2013-10-08T15:56:36+00:00] INFO: directory[/etc/sv/nginx/log] mode changed to 755
[2013-10-08T15:56:36+00:00] INFO: directory[/etc/sv/nginx/log/main] created directory /etc/sv/nginx/log/main
[2013-10-08T15:56:36+00:00] INFO: directory[/etc/sv/nginx/log/main] mode changed to 755
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/log/run] created file /etc/sv/nginx/log/run
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/log/run] updated file contents /etc/sv/nginx/log/run
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/log/run] mode changed to 755
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/log/config] created file /etc/sv/nginx/log/config
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/log/config] updated file contents /etc/sv/nginx/log/config
[2013-10-08T15:56:36+00:00] INFO: template[/etc/sv/nginx/log/config] mode changed to 644
[2013-10-08T15:56:36+00:00] INFO: link[/etc/init.d/nginx] created
[2013-10-08T15:56:36+00:00] INFO: runit_service[nginx] configured
[2013-10-08T15:56:36+00:00] INFO: link[/etc/service/nginx] created
[2013-10-08T15:56:41+00:00] INFO: runit_service[nginx] enabled
[2013-10-08T15:56:42+00:00] INFO: directory[/etc/postgresql/9.1/main] created directory /etc/postgresql/9.1/main
[2013-10-08T15:56:42+00:00] INFO: directory[/etc/postgresql/9.1/main] mode changed to 777
[2013-10-08T15:56:42+00:00] INFO: directory[/var/log/postgresql] created directory /var/log/postgresql
[2013-10-08T15:56:42+00:00] INFO: directory[/var/log/postgresql] mode changed to 777

================================================================================
Error executing action `create` on resource 'template[/etc/postgresql/9.1/main/postgresql.conf]'
================================================================================


Chef::Exceptions::UserIDNotFound
--------------------------------
cannot determine user id for 'postgres', does the user exist on this system?


Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/postgresql/recipes/server.rb

 66: template "#{node['postgresql']['dir']}/postgresql.conf" do
 67:   source "postgresql.conf.erb"
 68:   owner "postgres"
 69:   group "postgres"
 70:   mode 0600
 71:   notifies :restart, 'service[postgresql]', :immediately
 72: end
 73: 



Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/postgresql/recipes/server.rb:66:in `from_file'

template("/etc/postgresql/9.1/main/postgresql.conf") do
  owner "postgres"
  action "create"
  recipe_name "server"
  retry_delay 2
  cookbook_name :postgresql
  backup 5
  path "/etc/postgresql/9.1/main/postgresql.conf"
  source "postgresql.conf.erb"
  mode 384
  retries 0
  provider Chef::Provider::Template
  group "postgres"
  atomic_update true
end



[2013-10-08T15:56:42+00:00] INFO: Running queued delayed notifications before re-raising exception
[2013-10-08T15:56:42+00:00] INFO: template[nginx.conf] sending reload action to service[nginx] (delayed)
[2013-10-08T15:56:42+00:00] INFO: service[nginx] reloaded
[2013-10-08T15:56:42+00:00] INFO: bash[compile_nginx_source] sending restart action to service[nginx] (delayed)
[2013-10-08T15:56:44+00:00] INFO: service[nginx] restarted
[2013-10-08T15:56:44+00:00] ERROR: Running exception handlers
[2013-10-08T15:56:44+00:00] ERROR: Exception handlers complete
[2013-10-08T15:56:44+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-10-08T15:56:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
________________________________________________________________________________
| ~/code/balanced/billy @ mjallday-2 (master) 
| => 
```

I started with a clean slate by running `vagrant destroy && vagrant up`

**Comment by fangpenlin** [comment]
@mjallday Which billy-chef revision you are using? That chef repo build once failed on Travis CI, and I did some modification to postgresql cookbook, but it turns out it will fail in other environment, I recall the error you are seeing here is exactly the one I saw. So, I change it back then. Could you update the billy-chef to the latest revision on master branch and try again? It works fine on my Mac OSX environment.

**Comment by mjallday** [comment]
That seems to work for me. Thanks.

Before I close this ticket, is there anything else I need to do to get Billy running in vagrant? I just ssh'd in and don't seem to  see it running

``` sh
| ~/code/balanced/billy @ mjallday-2  (billy)(master) 
| => git submodule update --init --recursive
Submodule path 'chef': checked out '4c56799efe48dcc7a9292607f6e3b337bd53d088'
________________________________________________________________________________
| ~/code/balanced/billy @ mjallday-2  (billy)(master) 
| => vagrant up
Failed to load the "vagrant-butcher" plugin. View logs for more details.

Bringing machine 'default' up with 'virtualbox' provider...
[default] VirtualBox VM is already running.
________________________________________________________________________________
| ~/code/balanced/billy @ mjallday-2  (billy)(master) 
| => vagrant ssh
Failed to load the "vagrant-butcher" plugin. View logs for more details.

Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

147 packages can be updated.
66 updates are security updates.

Welcome to your Vagrant-built virtual machine.
Last login: Fri Sep 14 06:23:18 2012 from 10.0.2.2
vagrant@precise64:~$ ps aux | grep billy
vagrant  14304  0.0  0.2  11676   936 pts/1    S+   01:35   0:00 grep --color=auto billy
```

**Comment by fangpenlin** [comment]
@mjallday Did you run

```
vagrant provision
```

to make sure the chef is executed on that VM? Because your very first provision in `vagrant up` is aborted, you will need to run `vagrant provision` to rerun the chef again. 

If you did, there might be something wrong. I install the server at `/home/billy/billy_server` by default. I use [supervisor](http://supervisord.org) for running those servers. You can su into billy user and go into supervisors control console like this

```
sudo su - billy
supervisorctl -c ~/supervisord.conf
```

and all log records will go into `/home/billy/logs/`, you can also have a look in it, there might be leads for the problem.

**Comment by mjallday** [comment]
That's it!

```
vagrant@precise64:~$ ps aux | grep billy
billy    19083  0.0  3.2  51716 12136 ?        Ss   14:47   0:00 /usr/bin/python /usr/local/bin/supervisord -c /home/billy/supervisord.conf
billy    19100  0.1 10.8 157776 40508 ?        S    14:47   0:00 /home/billy/billy_server/env/bin/uwsgi --home=env --pidfile=web.uwsgi.pid --socket=/tmp/billy_web.sock --chmod-socket=666 --master --no-orphans --processes=2 --max-requests=10249 --module=wsgi
billy    19107  0.0  9.4 157776 35384 ?        S    14:47   0:00 /home/billy/billy_server/env/bin/uwsgi --home=env --pidfile=web.uwsgi.pid --socket=/tmp/billy_web.sock --chmod-socket=666 --master --no-orphans --processes=2 --max-requests=10249 --module=wsgi
billy    19108  0.0  9.4 157776 35384 ?        S    14:47   0:00 /home/billy/billy_server/env/bin/uwsgi --home=env --pidfile=web.uwsgi.pid --socket=/tmp/billy_web.sock --chmod-socket=666 --master --no-orphans --processes=2 --max-requests=10249 --module=wsgi
vagrant  19438  0.0  0.2  11680   936 pts/1    S+   14:59   0:00 grep --color=auto billy
```

Thanks @victorlin
